### ISSUE TITLE
Potential malware infecting make.exe

### ISSUE THREAD

**Issue by mhrecaldeb** [skeeto/w64devkit#100]
After downloading and unpacking the file [w64devkit-i686-fortran-1.21.0.zip](https://github.com/skeeto/w64devkit/releases/download/v1.21.0/w64devkit-i686-fortran-1.21.0.zip) , my antivirus detected and removed Trojan:Win32/CryptInject!MSR from w64devkit-i686-fortran-1.21.0\w64devkit\bin\make.exe 

My antivirus is Microsoft Defender in Windows 11, last updated 18/12/2023 5:59 GMT -5

It is advisable for you to take a look and make sure all files are safe to be used.
Regards
Mario

**Comment by skeeto** [comment]
This is a false positive. See #79 and #85, which, if you're so inclined, 
has steps to reproduce a bit-for-bit identical binary from the upstream 
sources.

**Comment by mhrecaldeb** [comment]
Thanks
