### ISSUE TITLE
Possible problem in archive

### ISSUE THREAD

**Issue by toncho11** [skeeto/w64devkit#101]
Please note that some antivirus programs are detecting a problem with: 1.21.0

zip file: [w64devkit-1.21.0.zip](https://github.com/skeeto/w64devkit/releases/download/v1.21.0/w64devkit-1.21.0.zip)

Infected file: bin\debugbreak.exe 
Reported by F-secure.

Try https://www.virustotal.com on the zip file.

It might be a false positive, but it is worth investigating.

**Comment by skeeto** [comment]
That's a false positive — virus scanners doing a poor job as usual. The 
entire program from entry point to exit is a mere 88 instructions, so with 
a bit of assembly knowledge and a few spare minutes, you could manually 
validate it (i.e. via objdump -d and -p). Unfortunately there's nothing I 
can do about the false positive.

**Comment by toncho11** [comment]
I see.
