### ISSUE TITLE
[Feature request] Ability to change console title from w64devkit.ini

### ISSUE THREAD

**Issue by MagicalDrizzle** [skeeto/w64devkit#115]
I frequently have both w64devkit and w64devkit-i686 open at the same time, and it can be difficult to check which window belong to which.
I propose the ability to configure the console title from the `w64devkit.ini` file, like this:
```ini
;home = ..\home
;home = %HOMEDRIVE%%HOMEPATH%
;title = w64devkit-i686
```
For now, a workaround I found is to simply change the code that set the console title: `SetConsoleTitleW(u"w64devkit-i686");`, and recompile.

**Comment by rmyorston** [comment]
It's possible to set the console title with:
```
printf "\033]0;w64devkit-i686\007"
```

**Comment by skeeto** [comment]
I've personally been using the escape sequence suggested by @rmyorston, 
but I like the idea of an .ini option as an alternative. The ini-title 
branch has an implementation I just whipped up, which I'll merge after 
further testing and review. I encourage you to try it out yourself! You 
don't even need to build the entire w64devkit to do so, just w64devkit.c.

**Comment by MagicalDrizzle** [comment]
They works fine for me!
Actually with this commit, this may have turned to a "general MinGW launcher", you can put w64devkit.exe and busybox into another mingw "distro", like winlib or llvm-mingw.
