### ISSUE TITLE
w64devkit-1.23.0.zip: 12 virus scanners at virustotal flag it

### ISSUE THREAD

**Issue by tmssngr** [skeeto/w64devkit#133]
https://www.virustotal.com/gui/file/5c7dce6762be3e0dba648a9317790444c0e2f1ef3e677315c115727d7a549539

**Comment by skeeto** [comment]
All false positives, though fortunately this particular listing doesn't 
include any trustworthy security software. The driver of these results 
appears to be debugbreak.exe (#132) and pkg-config.exe (both written by 
yours truly). Neither program changed in this release, so some incidental 
way that GCC 14 generates code matches entries across multiple databases, 
amplified by these EXEs being unusually lean.

Unfortunately there's nothing I can do about this. I've made everything 
about my builds as transparent as possible so that anyone can check and 
reproduce my work.

**Comment by davidstrahm** [comment]
Hi, I have installed the latest binaries last thursday on my windows machine.
Yesterday, suddenly my mouse startet moving by itself and windows opened everywhere and stuff started installing.

After rebooting, Windows defender isolated debugbreak.exe:
![image](https://github.com/skeeto/w64devkit/assets/16301487/df8dd0ea-e247-489b-8e36-3d90d9304c2b)

**Comment by Peter0x44** [comment]
"This program is dangerous and self-propagates over a network connection"
Utter nonsense. This is total worthless fearmongering and truly unacceptable.

**Comment by davidstrahm** [comment]
What do you mean? I am posting what happened, in an attempt to let the developer know there may be a problem. How is this "fearmongering and truly unacceptable" ?

**Comment by tmssngr** [comment]
What was surprising for me, was, that having downloaded the `w64devkit-1.23.0.zip` and uploaded to virustotal.com resulted in the above virus detection, but when I've told virustotal.com to verify the download URL https://github.com/skeeto/w64devkit/releases/download/v1.23.0/w64devkit-1.23.0.zip it did not show any thread: https://www.virustotal.com/gui/url/8bd03334f21f5f49af6b6f8e53075afbcaccee94cd225ee7968903aadfcee892

**Comment by edispring** [comment]
When downloading the zip and running `/bin/debugbreak.exe` through virustotal by its self the result is quite bad:
![image](https://github.com/skeeto/w64devkit/assets/5106463/3dedd12b-9c83-4eb8-ab58-0c7bd77f9d90)

**Comment by Peter0x44** [comment]
@davidstrahm I was referring to the nonsense message windows defender invents. It was not personal to you.

Either way - there is nothing any of us can do. debugbreak.exe is not malware. This message is false positive.

**Comment by MagicalDrizzle** [comment]
I have to say windows defender love tripping on w64devkit binaries - `make`, `debugbreak` etc

**Comment by jburn20** [comment]
Hi - any idea why debugbreak.exe is getting flagged as malware?

**Comment by Peter0x44** [comment]
@jburn20 go ask Microsoft. We aren't antivirus developers, there is nothing we can do.
This is not an issue.

**Comment by jburn20** [comment]
I understand that. I was just asking for any clarification on what the root cause might've been.

Thanks.

**Comment by skeeto** [comment]
False positive, see #79.
