### ISSUE TITLE
7zip and MalwareBytes detect potential malware

### ISSUE THREAD

**Issue by JonThomas801** [skeeto/w64devkit#143]
7zip wouldn't open w64devkit-1.23.0.zip as it thought is was a virus, so I performed a scan via MalwareBytes and it suspected that w64devkit/bin/debugbreak.exe was "Generic.Malware/Suspicious".

**Comment by grable0** [comment]
Its a known false positive. If you are still unsure, you could always verify its tiny source and compile it yourself.
