### ISSUE TITLE
Viruses?

### ISSUE THREAD

**Issue by techn0man1ac** [skeeto/w64devkit#154]
Hello. I have a problem.

I can't download from this link:

[https://github.com/skeeto/w64devkit/releases/download/v2.0.0/w64devkit-x64-2.0.0.exe](https://github.com/skeeto/w64devkit/releases/download/v2.0.0/w64devkit-x64-2.0.0.exe)

Google Chrome says it's a virus and won't let you download the program:

![Знімок екрана 2024-08-05 152122](https://github.com/user-attachments/assets/2035a0be-15be-4a28-83d6-8f63bc7d0b3d)

I checked the link use VirusTotal and it says all is well:

![Знімок екрана 2024-08-05 152416](https://github.com/user-attachments/assets/822bc7be-0831-45c3-88e9-c322491e33f8)

[https://www.virustotal.com/gui/url/4bff821231567fbe7765ee563a7953a0380279e83d87e0816baa37d298c977b6](https://www.virustotal.com/gui/url/4bff821231567fbe7765ee563a7953a0380279e83d87e0816baa37d298c977b6)

**Comment by skeeto** [comment]
Yeah, Chrome does its own screening in addition to the Windows stuff, but 
you should be able to override it with some effort. It will treat you like 
a child and fight you at each step, but ultimately you're in charge… for 
now. Look for the word "Keep" (at least in English locales) when you mouse 
over the download entry. It might be behind an ellipsis "more" button.

To see if I could figure out the "Keep" navigation, I just downloaded it 
in a fresh Windows+Chrome install, but it didn't stop me. So perhaps its 
reputation improved enough just now. Maybe your followup Virus Total scan 
gave it a clean bill of health. I believe its connected to Chrome's 
download screen after all.

**Comment by techn0man1ac** [comment]
Microsoft Edge says the same thing and won't let me download the file...
 However, the software author can manually write that it is an error:
[ https://feedback.smartscreen.microsoft.com/feedback.aspx]( https://feedback.smartscreen.microsoft.com/feedback.aspx)

**Comment by tdiz** [comment]
the same by Windows Security scanner
<img width="531" alt="Screenshot 2024-08-05 222110" src="https://github.com/user-attachments/assets/5e13addc-c30a-457d-b7e9-fc58bbefc821">

**Comment by Peter0x44** [comment]
@tdiz in this screen there is a way to click "allow" which should stop defender harassing you for this occasion.

**Comment by Teimir** [comment]
this is virus, probably repo is compromised
