### ISSUE TITLE
zip release

### ISSUE THREAD

**Issue by 3052** [skeeto/w64devkit#155]
I only see exe:

https://github.com/skeeto/w64devkit/releases/tag/v2.0.0

zip is nice so you can just extract and run like Linux

**Comment by ale5000-git** [comment]
In most cases the exe can still be extracted like an archive.
See: https://mshamory.medium.com/manually-opening-a-7-zip-self-extracting-archive-bfb2b6ae86b5

**Comment by 3052** [comment]
requires 7zip - which is just swapping one installer for another

**Comment by 0hip** [comment]
> I only see exe:
> 
> https://github.com/skeeto/w64devkit/releases/tag/v2.0.0
> 
> zip is nice so you can just extract and run like Linux

The .exe is not installer.
It is a self extracting archive.
![image](https://github.com/user-attachments/assets/f474c6a0-9458-49d5-bd4a-91deccbc1a70)
So after extracted you can "run like Linux"

**Comment by 3052** [comment]
OK, but they could also just distribute a zip file instead

**Comment by skeeto** [comment]
The new 2.x distribution is nothing more than a stripped-down 7-Zip, with 
custom icon, concatenated to a 7z archive which contains exactly the same 
contents as the original ZIP. It's done literally with "cat" here:

https://github.com/skeeto/w64devkit/blob/21177fbd/Dockerfile#L502

7z.sfx is a Windows subsystem EXE compiled like so (which you could do 
yourself in w64devkit to make any .7z self-extracting):

https://github.com/skeeto/w64devkit/blob/21177fbd/Dockerfile#L452-L457
https://github.com/skeeto/w64devkit/blob/21177fbd/src/7z.mak

It's not an installer. It doesn't touch the registry, create shortcuts, 
nor change anything outside the chosen destination, so it's no different 
than before except that Windows Explorer can't see inside it. If you have 
7-Zip installed, you can peer inside from the context menu: "7-Zip > Open 
archive".

If you're so inclined, you don't need to install 7-Zip either: There are 
portable 7-Zip distributions, and the official website offers a 7zr.exe 
command line tool which can manipulate w64devkit releases as archives. If 
you're on, say, Linux, the "7z" command can extract it without needing to 
use Wine to execute the self-extractor. (I do exactly this in a script to 
create my own w64dk "live CD" of w64devkit with my personal configuration 
baked in.)

**Comment by Peter0x44** [comment]
If you want a "portable" 7z extractor with a GUI I've found peazip to work the best.

**Comment by 3052** [comment]
these are all nice workarounds, but whats the point? the question should not be "why should we use Zip files?" the question should be "why should we not use Zip files?" using anything except zip is going to have a complexity cost, which should be justified

**Comment by Peter0x44** [comment]
Some of the rationale is explained in #87 . The file is smaller, and it extracts much faster than the zip support of windows.

I think this more than justified the "increased complexity".
The decision was made carefully, not on a whim.

**Comment by 3052** [comment]
the file is smaller, 35 MB vs 83 MB - however on my machine its an extract difference of 9s vs 8s, so only one second improvement. if youve carefully considered the options so be it, but know that when possible, I dont use any software thats distributed this way, including this one. so you are going to lose any users such as myself.

**Comment by Peter0x44** [comment]
1s improvement is still an improvement (it's a lot more than 1s for me).
And saving the bandwidth is important. You still haven't explained any technical reason why distributing as a 7z sfx causes such an inconvenience for you.

**Comment by 3052** [comment]
in general an exe has arbitrary system access, while a zip file is simply a container for files. in this case the exe might be "well behaved", but other than someone reading this thread, they would have no idea of knowing that. they would just have to trust that what they are running wont do anything stupid/wrong/annoying/damaging. with a zip you do not have that worry.

**Comment by garoto** [comment]
fwiw, I agree with the ~~89z~~ 3052 dude/dudette. The 7zip 50% size gains are nice, but it's kinda jarring to load the GH releases tab and see only .exe stubs.

**Comment by 3052** [comment]
please ignore @garoto - they are what happens when someone fails to get the mental health treatment they need 😂

**Comment by 3052** [comment]
please ignore @garoto - they are what happens when someone fails to get the mental health treatment they need 😂

in general an exe has arbitrary system access, while a zip file is simply a container for files. in this case the exe might be "well behaved", but other than someone reading this thread, they would have no idea of knowing that. they would just have to trust that what they are running wont do anything stupid/wrong/annoying/damaging. with a zip you do not have that worry.

**Comment by skeeto** [comment]
If you're extracting the original zip in 9 seconds (per your deleted comment) then you're not using Windows' built-in zip support. So continue with whatever archive tool you're already using for the new distribution format and you won't notice any difference. Rename `.exe` to `.7z` if it makes you feel more at home.

The Windows zip implementation is incredibly poor and [does not use buffering](https://textslashplain.com/2021/06/02/leaky-abstractions/). Its typical w64dk unzip times are 1 to 2 minutes. If you're on a fresh system, it's faster to open the zip in Explorer, pluck out `busybox.exe`, then in a regular console run `busybox unzip w64devkit.zip`. Further, Windows zip is buggy, and I've had to modify the distribution so that it wouldn't crash when unzipping w64dk (#58). That doesn't count any silent corruption that may have gone unnoticed. The new SFX distribution solves both these problems.

Files downloaded through a browser are given the [Mark of the Web](https://en.wikipedia.org/wiki/Mark_of_the_Web), and Windows zip applies it to files extracted from a marked archive. This taints the "installation" leading security tools to delete parts of it or slow it down, creating extra headaches for users. Most third-party archive tools, and more importantly the SFX stub, do not propagate the mark. The SFX distribution gives installations a clean bill of health without relying on third-party tools.

> I dont use any software thats distributed this way

If you're looking for prior art, Git uses exactly this format [for its official portable releases](https://git-scm.com/download/win) (since you're here on GitHub, surely you're using this!), and the *de facto* portable Python distribution [WinPython](https://winpython.github.io/) has been using it since before w64dk existed.

**Comment by MagicalDrizzle** [comment]
> If you're extracting the original zip in 9 seconds (per your deleted comment) then you're not using Windows' built-in zip support. So continue with whatever archive tool you're already using for the new distribution format and you won't notice any difference. Rename `.exe` to `.7z` if it makes you feel more at home.
> 
> The Windows zip implementation is incredibly poor and [does not use buffering](https://textslashplain.com/2021/06/02/leaky-abstractions/). Its typical w64dk unzip times are 1 to 2 minutes. If you're on a fresh system, it's faster to open the zip in Explorer, pluck out `busybox.exe`, then in a regular console run `busybox unzip w64devkit.zip`. Further, Windows zip is buggy, and I've had to modify the distribution so that it wouldn't crash when unzipping w64dk (#58). That doesn't count any silent corruption that may have gone unnoticed. The new SFX distribution solves both these problems.
> 
> Files downloaded through a browser are given the [Mark of the Web](https://en.wikipedia.org/wiki/Mark_of_the_Web), and Windows zip applies it to files extracted from a marked archive. This taints the "installation" leading security tools to delete parts of it or slow it down, creating extra headaches for users. Most third-party archive tools, and more importantly the SFX stub, do not propagate the mark. The SFX distribution gives installations a clean bill of health without relying on third-party tools.
> 
> > I dont use any software thats distributed this way
> 
> If you're looking for prior art, Git uses exactly this format [for its official portable releases](https://git-scm.com/download/win) (since you're here on GitHub, surely you're using this!), and the _de facto_ portable Python distribution [WinPython](https://winpython.github.io/) has been using it since before w64dk existed.

You know, when I suggested 7z SFX usage I honestly forgot that afterward these kind of discussions would be unavoidable...

**Comment by 3052** [comment]
@skeeto of course you are completely missing the point. its about trust. yes I CAN rename the file to 7z, but I shouldn't have to, you should just distribute it as a 7z file, and inform people that they can rename to EXE if they dont have 7zip installed. the current rename suggestion only works if someone visit this thread, otherwise the current exe appear identical to any other normal exe

also the Zip slams are red herring. nothing stopping from distributing a Zst file or choose your favorite compression. true Zst need 7zip or another program to extract, but I would 100% prefer a Zst file to an exe file, because again its just a dumb container instead of a program that can run arbitrary logic on my system.
