### ISSUE TITLE
GitHub issue?

### ISSUE THREAD

**Issue by ale5000-git** [skeeto/w64devkit#156]
GitHub no longer allow me to reply to this ticket: https://github.com/skeeto/w64devkit/issues/155
Is it a bug or I'm blocked?

See:
![ticket](https://github.com/user-attachments/assets/584bb6da-f566-45d7-b3b5-e32e2df70f57)

**Comment by garoto** [comment]
Might be the case that the issue author has blocked you. When that is the case, one can't reply and/or react to issues/prs made by the them.

**Comment by skeeto** [comment]
I suspect @garoto's explanation is correct, but in any case this has nothing to do with w64dk.
