### ISSUE TITLE
Feature Request: Please bring back the ZIP files

### ISSUE THREAD

**Issue by praynaud** [skeeto/w64devkit#157]
# Context

I am using the `w64devkit` in some GitHub actions that run on `windows-2022` using the pre-installed `powershell`. In general, I love it, it's great. Thank you!

# Problem

When trying to set up a `windows-2022` native `powershell` environment for `fortran` development, the `.exe` from your version 2.0.0 does not work at the command line. It is unclear whether it runs at all, but regardless, I am unable to then find the compiler and put it in my path.

# Potential Solution

The previous versions that used a `.zip` file (up to `1.23.0`) worked great.

Could you add a `.zip` asset to your 2.0.0 release and all subsequent releases?

**Comment by skeeto** [comment]
Despite the EXE extension, it's equally a 7z archive that can be accessed 
using any 7z-capable software. The self-extract executable attached to the 
archive is, by necessity of its GUI, a windows subsystem program which is 
why it doesn't play well with console programs. It's not possible to be a 
console subsystem program at the same time.

The first point is your solution. The 7-Zip "Download" page has "7zr.exe" 
(last item), a command line program to manipulate 7z archives. Put this in 
your build environment on your $PATH, then you can extract w64dk the same 
way you handled ZIP.

https://www.7-zip.org/download.html

Use the "x" option, as in:

7zr x w64devkit-x64-2.0.0.exe

This completely ignores the self-extract part, and when it completes 
everything works just like before with ZIP.

**Comment by praynaud** [comment]
@skeeto Thank you for the detailed explanation.

I will try your suggestion with 7zr and report back, but as stated in #158 the self-extracting archive is also causing some false security issues, hence perhaps not a bad thing to have both the self-extractor and the zip files... although I do understand this does result in some additional work and some duplication.

In any case, thanks again!

**Comment by Peter0x44** [comment]
The zip also caused numerous "false security issues" too. So nothing really regressed.

**Comment by praynaud** [comment]
@Peter0x44 Fair enough...

**Comment by skeeto** [comment]
Yup, as @Peter0x44 said, ZIP has the same problems (#79) but worse since 
it's multiplied by a hundred EXEs in the distribution, any of which can 
set off false alarms. The self-extracting archive should be a slight 
improvement because it's a single point of contention for "security" 
scanners, and when extracting it doesn't propagate the Mark of the Web 
into the installation.

**Comment by praynaud** [comment]
@skeeto I have tried the 7zip option you proposed and can confirm that it works both locally in in GitHub actions.  As far as I am concerned, this issue can be closed: you have resolved my problem.

Thanks!

**Comment by skeeto** [comment]
Thanks for following up, @praynaud! I really appreciate it.
