### ISSUE TITLE
w64devkit issue 

### ISSUE THREAD

**Issue by yasieb** [skeeto/w64devkit#163]
hi there what i mean was
can i install pro tools  without to instal it on my system windows 10 
![105014988-575cb680-5a41-11eb-90d5-d942d28184b2](https://github.com/user-attachments/assets/5be1c85b-2ca4-41bd-98f6-190a93b0e2e4)

please dont close my issue

**Comment by yasieb** [comment]
i want a clean  drive instalation because i dont want cubase as a exe onnmy desktop pc

**Comment by skeeto** [comment]
Please continue the discussion on #161.
