### ISSUE TITLE
Windows detects w64devkit-x64-2.0.0.exe as PUA:Win32/GameHack

### ISSUE THREAD

**Issue by 3esmit** [skeeto/w64devkit#167]
Downloaded from GitHub

![image](https://github.com/user-attachments/assets/69acefba-6ab8-440d-af83-360a145feb4d)

**Comment by 3esmit** [comment]
See other antivirus https://www.virustotal.com/gui/file/cea23fc56a5e61457492113a8377c8ab0c42ed82303fcc454ccd1963a46f8ce1

**Comment by skeeto** [comment]
These are all false positives and unfortunately there's nothing I can do about it. See #158, #154. You'll need to disable/bypass your virus scanner.
