### ISSUE TITLE
Please add lld

### ISSUE THREAD

**Issue by mh466lfa** [skeeto/w64devkit#170]
I can confirm this issue: https://github.com/brechtsanders/winlibs_mingw/issues/118. GNU ld is extremely inefficient.

p/s: I only ask for lld, not the full LLVM or Clang.

**Comment by skeeto** [comment]
It's at least worth investigation, though I don't know when I'll get to it 
myself. I haven't noticed performance issues with ld in w64dk so far, but 
I haven't been linking gigantic C++ images (using Boost, etc.). Do you 
know a public project I could try that shows a significant difference 
between ld and lld? A contrived example would be fine; even preferable.

For those following along: If you have Visual Studio installed with the 
Clang component, in a vcvars environment you can -fuse-ld=lld in w64dk to 
link with lld. It works fine for C programs, though it struggles linking 
libstdc++, perhaps related to Bintuils #26103. (Probably an issue that 
would need to be solved here.) It's one way to get a sneak peek of lld in 
w64dk.

**Comment by chatchoi** [comment]
> Do you know a public project I could try that shows a significant difference between ld and lld?

CopperSpice comes immediately to mind.

**Comment by mh466lfa** [comment]
Yes, CopperSpice. You don't need to build the library from source. You can use their prebuilt library (MinGW version) and try to build their sample program, KitchenSink. Please note that you need to use a different MinGW, e.g., their own MinGW distro on their website. Yours will not work because it's lacking dynamic libraries (libstdc++, libwinpthread,...). I used to try compiling CopperSpice (the library) in MSYS2. Even though I have plenty of RAM, `ld` ate many GBs of memory and stuck for hours. Switching to `lld` solved the problem immediately. Linking time from hours now only takes minutes.

**Comment by skeeto** [comment]
Thanks, this seems like the sort of example I want!

**Comment by chatchoi** [comment]
A bit off-topic but this is my experience: Clang is more memory efficient than GCC, even on Unix. For example, the system has 4 cores and 8GB of RAM, by default `ninja` will launch 6 make jobs (1.5*number of cpu cores). This will only work with Clang. For GCC, you have to limit it to just 4 make jobs. Otherwise you will encounter OOM.

**Comment by Peter0x44** [comment]
One thing worth mentioning is that lld doesn't support GCC lto, though that is disabled in w64devkit anyway. If mold ever begins supporting PE I think it will be the better choice here.

**Comment by mh466lfa** [comment]
> Does lld still only supports linker scripts on ELF targets? If that's the case, that'd be a deal breaker for me

You don't need it but I need. This FR is about adding lld, not removing GNU ld, so feel free to use whatever you want to use.
