### ISSUE TITLE
Loading ../src/profile

### ISSUE THREAD

**Issue by ale5000-git** [skeeto/w64devkit#174]
Instead of patching the BusyBox executable to load `../src/profile` isn't simpler to create an `etc/profile` script file that just source the `../src/profile` file?

**Comment by skeeto** [comment]
See the discussion on #162. If anything `../etc/profile` would be most conventional. In this case it's not a user-facing configuration and not meant to be edited in the installation. It exists to work around an `ash` limitation: It's not possible to set lowercase environment variables, needed for Autotools, externally to the shell. It would make more sense for me to ditch the name `profile` entirely and name it `src/autotools-config`.
