### ISSUE TITLE
Commit message is wrong

### ISSUE THREAD

**Issue by ale5000-git** [skeeto/w64devkit#175]
Here: https://github.com/skeeto/w64devkit/commit/11c8495d0fb3e7482f042705b445ed497c679dd3
the message is `Upgrade to busybox-w32 FRP-5398-g89ae34445`.

But the version is effectively 5467-g9376eebd8.

**Comment by skeeto** [comment]
Thanks for pointing this out. Nothing I can do to change the commit message, unfortunately, so I'll just have to watch for it next time. The busybox-w32 version numbers are a bit too large and too far apart to keep in my short term memory, so I rely on the clipboard and must have copied from the wrong place.

**Comment by Peter0x44** [comment]
`git commit --amend` and then a force push would have sorted it.

**Comment by skeeto** [comment]
Barring an emergency, I don't want to rebase the master branch. It's too 
disruptive. Anyone who pulls it would need to manually hard reset their 
local master branches to match.

(In contrast, I'm perfectly comfortable with radically rebasing feature 
branches without notice. I do it all the time.)
