### ISSUE TITLE
False Positive Reason

### ISSUE THREAD

**Issue by SpyterDev** [skeeto/w64devkit#179]
I know that Windows falsely detects w64devkit as malware, but I was curious of the reason why. Usually a false positive is 1-4 detection but in VT it's 20. Is it just the way the binary is compiled because I had a similar problem before with mingw before?

**Comment by rfl890** [comment]
Maybe 7zip sfx are commonly used to distribute malware, so it's being flagged. Just a guess.

**Comment by 0hip** [comment]
> I know that Windows falsely detects w64devkit as malware, but I was curious of the reason why. Usually a false positive is 1-4 detection but in VT it's 20. Is it just the way the binary is compiled because I had a similar problem before with mingw before?

https://www.virustotal.com/gui/url/4bff821231567fbe7765ee563a7953a0380279e83d87e0816baa37d298c977b6

![image](https://github.com/user-attachments/assets/0510dfc6-7556-443b-a4d8-f36b19dc9c63)

**Comment by rfl890** [comment]
I think original author means the VT analysis of the actual file: https://www.virustotal.com/gui/file/cea23fc56a5e61457492113a8377c8ab0c42ed82303fcc454ccd1963a46f8ce1
![{46E8DB3C-62A8-46CF-9FB9-FD355245E565}](https://github.com/user-attachments/assets/d0a1af85-8c08-437a-94b4-997dd43b6cd1)
