### ISSUE TITLE
Viruses were found in 2.00 version

### ISSUE THREAD

**Issue by cpgitgig135** [skeeto/w64devkit#184]
I downloaded the w64devkit-x64-2.0.0.exe file from https://github.com/skeeto/w64devkit/releases/download/v2.0.0/w64devkit-x64-2.0.0.exe and ran Avast Antivirus, which found 2 viruses.

**Comment by skeeto** [comment]
There are no viruses. These are false positives. See #154, #158, #167, #176.

**Comment by Peter0x44** [comment]
@cpgitgig135 You should probably get rid of Avast anyway...
https://www.theverge.com/2024/2/22/24080135/avast-security-privacy-software-ftc-fine-data-harvesting
