### ISSUE TITLE
how to set "w64devkit" to open the current directory ?

### ISSUE THREAD

**Issue by chshwei-cn** [skeeto/w64devkit#186]
for example, in "d:/dir1/dir2" to execute w64devkit.exe , w64devkit terminal is located in "d:/dir1/dir2"?

**Comment by grable0** [comment]
Thats what the profile is for.   For example, i made mine cd to any directory its pointed at, even running binaries.
I use that to start a terminal from explorer anywhere i want.

**Comment by skeeto** [comment]
w64devkit.exe starts a busybox-w32 shell with "sh -l" (i.e. a login shell) 
which unconditionally changes the working directory to the home directory, 
so it's currently not possible to invoke w64devkit.exe and preserve your 
working directory in the newly launched shell.

As @grable0 said, if you always want to start in a particular location 
other than $HOME then you can "cd" in your .profile. Or even set that 
location to $HOME (or via w64devkit.ini) in the first place, making it 
your home directory.

The important tasks for w64devkit.exe are setting $PATH and starting a 
shell. The rest is gravy. You can do those first yourself by placing 
w64devkit's "bin/" directory to your PATH by some other means, then for 
the second run "sh" (without "-l") to get a non-login shell. This will not 
load .profile but will leave your current working directory unchanged.
