### ISSUE TITLE
Does Mingw GCC support C++23 std::mdspan?

### ISSUE THREAD

**Issue by NiKeYiGuN** [skeeto/w64devkit#188]

**Comment by skeeto** [comment]
Mingw-w64 has nothing to do with it, and this is up to libstdc++, part of 
GCC. It appears mdspan is not yet implemented by libstdc++:

https://en.cppreference.com/w/cpp/compiler_support
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107761
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html

**Comment by NiKeYiGuN** [comment]
3q
