### ISSUE TITLE
New mingw-w64 8.0

### ISSUE THREAD

**Issue by turboautiste** [skeeto/w64devkit#2]
A new mingw version was released recently so I was wondering if you planned on updating the Dockerfile appropriately ?

I did so myself and tried building it with the Dockerfile as is but I got a compilation error related to some cryptic header file which I don't think could solve by myself. If you could look into it, it would be greatly appreciated !

**Comment by skeeto** [comment]
I do intend to follow Mingw-w64 releases as they come out. However, I 
think I ran into the same compilation problem, and it seems 8.0.0 is 
simply broken.

https://sourceforge.net/p/mingw-w64/bugs/853/

This sort of issue isn't unusual for Mingw-w64, and I'll just wait for 
8.0.1 or whatever release fixes it.
