### ISSUE TITLE
collect2.exe: fatal error: cannot find 'ld' compilation terminated.

### ISSUE THREAD

**Issue by Mochongli** [skeeto/w64devkit#25]

**Comment by skeeto** [comment]
What command lead to this result and how/where did you run it? This error 
might happen if w64devkit.zip was only partially unzipped, if GCC was 
invoked in some odd way, or if you've got a blend of toolchains in your 
path.

**Comment by Mochongli** [comment]
> What command lead to this result and how/where did you run it? This error might happen if w64devkit.zip was only partially unzipped, if GCC was invoked in some odd way, or if you've got a blend of toolchains in your path.

-fuse-ld=mold
