### ISSUE TITLE
Include the nano text editor

### ISSUE THREAD

**Issue by 2cls0f** [skeeto/w64devkit#40]
I have always used the nano text editor. I learned how to use Linux and the shell on various online tutorials, all of them use the nano text editor. I don't know how to use vi/vim other than how to exit it. Please consider adding the nano text editor. Thank you.

**Comment by 2cls0f** [comment]
https://github.com/lhmouse/nano-win

**Comment by 2cls0f** [comment]
https://github.com/okibcn/nano-editor

**Comment by garoto** [comment]
> As far as I know there is no native Nano port for Windows. It only runs on Cygwin or MSYS2 [...]

mingw-w64 nano compiles do exist and they can be found here: https://github.com/lhmouse/nano-win/

It's a statically linked binary sitting at around ~750kB. I assume it can easily be bundled by the user himself into a portable zip thingy if desired.

**Comment by skeeto** [comment]
Thanks for the links. That's interesting to know.

It's unfortunate both still require MSYS2 for building, so even with the 
sources and w64devkit you still can't readily compile your own nano. (If 
that sounds unreasonable, bear in mind that it's easy to build Vim from 
source using only w64devkit.)
