### ISSUE TITLE
Translate Windows path to Posix style path automatically

### ISSUE THREAD

**Issue by 2cls0f** [skeeto/w64devkit#41]
For example, I pasted the Windows path copied from Windows Explorer, there should be a shortcut keys to automatically translate it to Posix style path. Another solution is including a cygpath like utility. Please consider. Thank you.

**Comment by rmyorston** [comment]
If you just want to convert the backslashes to forward slashes in the pasted path, the shell in busybox-w32 lets you do that with Ctrl-Z.

**Comment by skeeto** [comment]
Thanks, Ron, I didn't know about that! Handy!
