### ISSUE TITLE
Add a w64devkit version that also bundled Clang

### ISSUE THREAD

**Issue by 2cls0f** [skeeto/w64devkit#43]
Inspired by winlibs.com's distribution and w64devkit's -fortran version. This Clang also uses binutils, libstdc++ and other GCC tools so it will not add much space.

**Comment by skeeto** [comment]
While #44 makes some sense as another "flavor" of w64devkit, bundling a 
second, superfluous compiler isn't aligned with my goals for the project 
even if it shares the rest of the toolchain.
