### ISSUE TITLE
pacman?

### ISSUE THREAD

**Issue by nerdralph** [skeeto/w64devkit#5]
I'm not sure if it fits with your design goals or not, but have you considered including pacman?  I think that would make it a lot easier to add other tools.

**Comment by skeeto** [comment]
A primary goal of w64devkit is support for fully offline development, an 
area I feel has been neglected. An internet connected package manager that 
depends on external services doesn't fit with this goal. That domain is 
already well-covered by MSYS2, so I'll leave it to them.

Besides, I have a rustic vision of a team choosing w64devkit as the 
toolchain for their project. It will never change nor surprise them with 
"updates", and everything they need is packed away in a .zip that they can 
archive alongside their project. Unlike a lot of software, they would 
never lose the ability to compile from source. Introducing a package 
manager undermines this idea and creates the temptation to introduce 
unnecessary dependencies.

**Comment by nerdralph** [comment]
OK, thanks for the explanation.  I was looking for an easy way to add clang/llvm.
