### ISSUE TITLE
Make tool Windows 11 CreateProcess stucks 

### ISSUE THREAD

**Issue by bazilxp** [skeeto/w64devkit#63]
Trying to compile  llama.cpp https://github.com/ggerganov/llama.cpp

What come across , checked the Makefile , there are some (uname ) e.t.c. none of them work well (stuck ) 

make tool , is invoking CreateProcess ( and it's never quit :( )  ,manually terminating process(uname ) bring another e.t.c. so never works well for spawning proceses. 

1.17 ,1.18,1.19 , no luck same issue with make tool :( 

C:/Development/ML/llama.cpp $ make --no-silent  -d
GNU Make 4.4
Built for x86_64-w64-mingw32
Copyright (C) 1988-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
find_and_set_shell() path search set default_shell = C:/Development/ML/w64devkit/bin/sh.exe
Reading makefiles...
Reading makefile 'Makefile'...
CreateProcess(C:\Development\ML\w64devkit\bin\uname.exe,uname -s,...)

Simple application "hello-world.c"  can compile.. I suspect something has been "changed" with "CreateProcess" since make tool not works well...

**Comment by bazilxp** [comment]
Bug not reproducible on windows 10 machine...

**Comment by skeeto** [comment]
I suspect it's something particular to that machine. Perhaps a security 
tool doesn't like w64devkit's uname.exe and is blocking its load, or it 
hooks CreateProcess and won't allow make.exe to call it. I cannot think of 
a reason why this problem might occur, nor can I reproduce the issue on 
Windows 11. Perhaps check the event logs for anything unusual.

**Comment by bazilxp** [comment]
Checked event viewer, did not found any suspicious records. When i replaced uname( with uname from msys) it's passing this step, next place where it's stuck invoking the CC.   changed CC=GCC CXX=g++ , partially compile and stuck .
Thanks for the answer, we can proceed with closure of this issue.

**Comment by bazilxp** [comment]
Windows nature, which is hard to deal , toolchain works. Problems with workstation itself
