### ISSUE TITLE
Bat support

### ISSUE THREAD

**Issue by lesleyrs** [skeeto/w64devkit#64]
Why use such an old "less" version? It's incompatible with things like https://github.com/sharkdp/bat

If there's a reason for it, then no worries.

**Comment by lesleyrs** [comment]
I re-installed git and selected add unix tools to path, it seems it will use the git version over the w64devkit less now even though they have name conflicts.

**Comment by lesleyrs** [comment]
Git adds too many tools, I'd still prefer having an updated version of less here.

Using this https://github.com/jftuga/less-Windows for now.

**Comment by lesleyrs** [comment]
@skeeto Any interest in bumping less version in w64devkit?

**Comment by grable0** [comment]
Since w64devkit uses busybox which includes `less` it will probably stay the way it is.
You could always just delete or rename the alias `less.exe` in the bin directory and your `less` further down the path will get picked up instead.

**Comment by lesleyrs** [comment]
Ah ok I didn't realise busybox included less, thanks.
