### ISSUE TITLE
Can you build gcc with mcf

### ISSUE THREAD

**Issue by eko5624** [skeeto/w64devkit#70]
I can cross-compile gcc with posix thread.
LINK here: https://github.com/eko5624/toolchain-test/discussions/6#discussion-5289277

But I tried to cross-compile gcc with mcf, something is wrong.
LINK here: https://github.com/eko5624/toolchain-test/discussions/5#discussioncomment-6144234
Any suggestions?

**Comment by skeeto** [comment]
Sorry, I have no experience with mcfgthread, and this is the first time 
I've even heard of it.

**Comment by eko5624** [comment]
Done! 
https://github.com/eko5624/toolchain
