### ISSUE TITLE
fatal error C1189: #error: Your C implementation is not IEC 559 compliant, which is required for proper Vulkan interop

### ISSUE THREAD

**Issue by JianbangZ** [skeeto/w64devkit#73]
happened When I tried to use CMake to use Vulkan APIs. Looks like a compiler issue in w64devkit

**Comment by skeeto** [comment]
Are you sure you're invoking the right compiler? C1189 is an MSVC error 
code, and that's a Visual Studio error message.

**Comment by JianbangZ** [comment]
Yes you are right, it's a MSVC issue. Thanks
