### ISSUE TITLE
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum "/src/w64devkit.ini": not found

### ISSUE THREAD

**Issue by Eutropios** [skeeto/w64devkit#74]
When running `docker build -t w64devkit .`, the following error shows up:
```bash
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 76b4246f-5533-4f81-bb8c-192e65c3094a::jcdnanu2d8rzw0lxfj2xffw6m: "/src/w64devkit.ini": not found
```
Solution to fix:
Move the `w64devkit.ini` file from the top-most directory into `./src`.

**Comment by Tobi823** [comment]
I had the same issue. I downloaded https://github.com/skeeto/w64devkit/releases/download/v1.20.0/w64devkit-1.20.0.zip, extracted the zip archive, entered the extracted archive and tried to run "sudo docker build -t w64devkit ."

**Comment by Tobi823** [comment]
![image](https://github.com/skeeto/w64devkit/assets/10066140/8e4fb944-9efa-427b-ac8c-168a87dbb470)

When I open the ZIP archive you see, that w64devkit.ini is not in the right place.

**Comment by skeeto** [comment]
Thanks, that clears things up: You're running Docker for no reason. That's 
just a temporary, disposable build environment, but you've downloaded a 
completed build. Just use it. No Docker necessary. If you want to build 
from source, use the repository. I include all the necessary pieces to 
rebuild from an existing build, mainly as a kind of documentation, but 
that's not the intended use.
