### ISSUE TITLE
Windows says Zip-File is empty

### ISSUE THREAD

**Issue by Rick-Schirmer** [skeeto/w64devkit#76]
Hey, after running the docker build and ducker run, when trying to unzip the file, it seems to always says is empty, no matter if I am using 7zip or windows .zip, it does not believe it is a zip file.

Windows:
<img width="649" alt="image" src="https://github.com/skeeto/w64devkit/assets/77794143/236e3bad-6ede-4a5e-8930-22c48e3b2de2">
Sorry, windows is German, but as said, the translation says: The zip folder is empty.
7zip:
<img width="718" alt="image" src="https://github.com/skeeto/w64devkit/assets/77794143/485c37e2-98df-4317-94ca-9eb12eea2e9c">
Says: Not an archive.

I did not get any error-messages during the build or running it.

**Comment by rmyorston** [comment]
Related to issue #69, perhaps?

**Comment by Rick-Schirmer** [comment]
Ooof, sounds like it, I am sure I used powershell... Gonna try it with cmd and see if it fixes it. Sorry missed to go through the closes issues.
