### ISSUE TITLE
how to make a script via bat?

### ISSUE THREAD

**Issue by intulint** [skeeto/w64devkit#80]
I tried but apparently my knowledge is not enough. How can I make a script to run? It all ends with just opening the program. I don't understand how to pass commands from the script to the program.

**Comment by Peter0x44** [comment]
To run what? What are you trying to write a script to do?

**Comment by intulint** [comment]
@Peter0x44 just a .bat file for win10 to automatically rebuild the project after the update. 
I don't know how to pass w64devkit.exe command which is run in this script.

**Comment by Peter0x44** [comment]
Perhaps you want to add the "bin" directory from the w64devkit zip to your PATH, then you can execute `gcc` from a cmd.exe shell.

What is "the project" you're referring to here?

**Comment by intulint** [comment]
@Peter0x44,  I wanted to automate the build of llama.cpp и other similar projects. Yes, I managed to run the make command from the console after calling - "set PATH=c:\path\to\w64devkit\bin;%PATH%".  The project was assembled crookedly, but this is not a problem with this kit. Thanks for the help
