### ISSUE TITLE
ld error: multiple definition of `std::type_info::operator==(std::type_info const&) const`

### ISSUE THREAD

**Issue by xparq** [skeeto/w64devkit#86]
**w64devkit 1.20.0**, both 32/64 bit
  _(Tried to check with gcc12 in an older `w64devkit` which I also have here, but the project that triggers it depends on `<format>`.)_

* Does not happen with a stock Debian stable on WSL, using GCC 13.2 (installed from `testing`): `g++ (Debian 13.2.0-2) 13.2.0`
* Same project builds clean with MSVC.
* It's a single compilation unit.
* I've been using [doctest](https://github.com/doctest/doctest), but it didn't cause any issues earlier, and I don't think I've changed anything related.
* I noticed this error a little while after adding `std::regex` stuff to the code. Not sure yet if that's related, I might test it out, if this doesn't seem familiar from elsewhere/upstream. _(I've seen multiple vaguely similar reports for GCC etc., but the best matches were unanswered SO questions. [Answered [one](https://stackoverflow.com/questions/76297301/multiple-definition-error-when-statically-linking) in the meantime.])_
* The project can afford `-fno-rtti`, so that's a viable workaround for me.

~~~~
g++ -Wall --std=c++23 test.cpp
.../ld.exe: .../w64devkit/gcc13/64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/libstdc++.a(tinfo.o):tinfo.cc:
(.text$_ZNKSt9type_infoeqERKS_+0x0): multiple definition of `std::type_info::operator==(std::type_info const&) const';
...\Temp\ccOVUCq4.o:test.cpp:(.text$_ZNKSt9type_infoeqERKS_[_ZNKSt9type_infoeqERKS_]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
~~~~
<sup>&nbsp;&nbsp;_(Edited for readability.)_</sup>

**Comment by xparq** [comment]
Yup, confirmed; this single line triggers it:

    std::regex regx("");

Probably the regex compiler. (Just `std::regex regx();` is not enough.)

**Comment by skeeto** [comment]
This appears to be a bug in libstdc++, perhaps related to static linking, 
which would explain why it's mostly gone unnoticed. (w64devkit's static 
linking libstdc++ is unusual.) I can reproduce it from the cppreference 
std::type_info::operator== example, even when reduced to:

#include <typeinfo>
int main() { return typeid(0) == typeid(0); }

It only occurs with -std=c++23, e.g. no problem with -std=c++20. Same goes 
for your std::regex example.

libstdc++ tinfo.cpp refuses to compile when "__cplusplus > 202002L" added 
in 3633cc54, which is also present in GCC 12. And indeed, the same bug 
occurs in GCC 12 (w64devkit 1.18.0). It also occurs from the w64devkit 
bootstrap cross-compiler. I can't find any upstream reports for this bug.

**Comment by xparq** [comment]
Thanks for the investigation. I still wonder why the same static-linking command with `c++23` still works on Debian for the (~same) g++ version (`lib32stdc++6 (13.2.0-2)`). 

_(Tried to find something in `/usr/share/doc/gcc-13-base/*Debian*`, but couldn't.)_

**Comment by Peter0x44** [comment]
> I can't find any upstream reports for this bug.
I believe this has been reported upstream, albeit in a different context
I noticed it when I went to open a bug myself
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110572

**Comment by skeeto** [comment]
Ah, wonderful, thanks @Peter0x44! That looks to be exactly this issue.

**Comment by xparq** [comment]
Shall we close this as "not planned"?

**Comment by skeeto** [comment]
One of the benefits of running your own distribution is that you can 
easily patch anything to your heart's content, so we can nip this in the 
bud before the GCC project gets around to fixing it. 731cbdb is a keyhole 
solution to always enable "new" inline semantics for this operator, not 
only under C++23. It fixes the problem here as far as I can tell. The cost 
is breaking C++ ABI compatibility with object files from older w64devkit 
releases that did not use -std=c++23. C++ ABI breakage is generally true 
across w64devkit releases spanning major GCC releases, so I don't view 
that as a big deal.

Before I merge it, more testing would be nice. If there's some important 
detail I'm missing, definitely let me know. (I am simply not intelligent 
enough to be confident about the correctness of anything involving C++, so 
there's always some guesswork.)

**Comment by xparq** [comment]
I'm not even intelligent enough to build it from source. ;) But if you can link me up with a download, I'd happily start using it.

**Comment by Peter0x44** [comment]
> I'm not even intelligent enough to build it from source.
If you have docker, check the README. It's not difficult, it does not require "intelligence".

**Comment by xparq** [comment]
I know it's not difficult; that smiley for "intelligence" was meant to refer to the fact that I don't really have Docker.

(I may be even more frugal/old-school than you are in this regard. I mean I don't even have a Raspberry 4...)

Seriously though, this old laptop I'm on, albeit weaker than my phone*, could probably run Docker, of course, and I've even installed "something docker" a while ago to WSL, but it's like Java in the decades: I knew it was out there, and everybody used it, but... (The difference is that I'm not purposefully avoiding Docker, I'll eventually get around to learning/using it (even used to tinker with laughable approximations of it in the past century, before proper OS support existed). "Just not this week.".)


\* <sup>_I also know that I could build on my phone then (did that to other things), but I've recently broken its screen._</sup>

**Comment by xparq** [comment]
Oh, just noticed the (no longer that) new release! <3

Confirming that it has indeed fixed the issue for me, too.

<sub>_(I don't know about your issue workflow preferences, but the fact that it has been kept open long after even releasing the fix suggests to me that it may be my job to verify it -- and then possibly even closing the thing? (Would be cool if GitHub supported issue policies, at least in the form of just a link to the repo wiki; whatever... I'm just rambling, because I should be working otherwise. :) Thanks for the release!)_</sub>

**Comment by skeeto** [comment]
Thanks for the followup, @xparq! I'll close this out.
