### ISSUE TITLE
32bit version of 1.20.0 - make is reported as virus

### ISSUE THREAD

**Issue by MrMadguy64** [skeeto/w64devkit#93]
My anti-virus says make.exe is Trojan:CryptInject. 1.19.0 has the same version of Make (i.e. 4.4), but it doesn't happen. Can you check it, please?

**Comment by skeeto** [comment]
That's a false positive. Per #79 and #85, you can readily verify this 
yourself without trusting me by building a make.exe from source. You'll 
get a bit-for-bit identical binary, and all the inputs — aside from the 
easily-audited build script — will be sourced from upstream projects, 
namely Debian's GCC toolchain (for bootstrap) and GNU-distributed source 
tarballs.

**Comment by GizmoGitHub** [comment]
nearly same issue there
![image](https://github.com/skeeto/w64devkit/assets/7433746/d0b3cede-bc05-4740-a55b-29e84cd4eaf1)
